//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class registered_tag
    {
        public long ID { get; set; }
        public int tagid_fk { get; set; }
        public long student_fk { get; set; }
        public sbyte enabled { get; set; }
    
        public virtual student student { get; set; }
        public virtual tagid tagid { get; set; }
    }
}
