//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class registered
    {
        public int id { get; set; }
        public int years_fk { get; set; }
        public byte school_fk { get; set; }
        public byte class_fk { get; set; }
        public long student_fk { get; set; }
        public sbyte enabled { get; set; }
    
        public virtual academic_year academic_year { get; set; }
        public virtual classroom classroom { get; set; }
        public virtual school school { get; set; }
        public virtual student student { get; set; }
    }
}
